### ISSUE TITLE
The name of this project masks https://github.com/webpy

### ISSUE THREAD

**Issue by cclauss** [User0332/webpy#1]
https://github.com/webpy was created by https://en.wikipedia.org/wiki/Aaron_Swartz and continues to be the operating platform for https://openlibrary.org and other major projects so please change the name of this project to something that does not conflict.
@webpy/webpy-core, @openlibrary

**Comment by User0332** [comment]
I'm not sure I understand the issue - The projects themselves have distinct names (WebPy vs web.py), are found at distinct locations, and have distinct package names on PyPI. I don't see an issue if they have the same repository name. Additionally, this project isn't really prevalent so it seems unlikely that it would interfere at all.
